### ISSUE TITLE
PoissonPointProposal is not necessarily symmetric.

### ISSUE THREAD

**Issue by mikkelbue** [mikkelbue/tinyDA#47]
Force `p_create = p_destroy` to make PoissonPointProposal guaranteed symmetric.

**Comment by SaiAakash** [comment]
Should this go into the `make_proposal` function of the `PoissonPointProposal` class ? This would just require a statement that assigns the same value to the `create` and `destroy` moves before the random selection statement. Is that right ?

**Comment by mikkelbue** [comment]
@SaiAakash thanks for looking into this. I would probably just put in an assertion in the `__init__` method to only allows for having equal probabilities for `create` and `destroy`.

**Comment by SaiAakash** [comment]
Cool !

**Comment by SaiAakash** [comment]
Hi @mikkelbue ! There is a pull request #54 addressing this issue now.

**Comment by mikkelbue** [comment]
Closing with https://github.com/mikkelbue/tinyDA/pull/54
