### ISSUE TITLE
Allow for evaluating the posterior.

### ISSUE THREAD

**Issue by mikkelbue** [mikkelbue/tinyDA#48]
At the moment you can evaluate the posterior by calling `log_posterior_test = my_posterior.create_link(parameters_test).posterior`, which is a little roundabout.

This could be replaced with a shortcut.

**Comment by SaiAakash** [comment]
Do you think it's okay to wrap the statement in your message above, into a method of the posterior class ?

**Comment by mikkelbue** [comment]
Hi @SaiAakash thanks for picking up on this.

Yes, I think that would be ideal. Maybe as a method `Posterior.logpdf(x)`, and perhaps also a `__call__()` method that just evokes `logpdf`.

**Comment by SaiAakash** [comment]
The `logpdf` method you have suggested is a separate from the `Posterior.posterior_eval` function right ?

**Comment by mikkelbue** [comment]
@SaiAakash No I meant that the method should be called `logpdf`, to conform to the `scipy` convention.

**Comment by SaiAakash** [comment]
Got it !

**Comment by mikkelbue** [comment]
Fixed with https://github.com/mikkelbue/tinyDA/pull/52
